name: ENTSOE Data Job

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ENTSOE job
        env:
          ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
          SUPABASE_CONN: ${{ secrets.SUPABASE_CONN }}
        run: |
          python entsoe_job.py
