name: ENTSOE ETL

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL
        env:
          ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
          AZURE_PG_HOST: ${{ secrets.AZURE_PG_HOST }}
          AZURE_PG_DB: ${{ secrets.AZURE_PG_DB }}
          AZURE_PG_USER: ${{ secrets.AZURE_PG_USER }}
          AZURE_PG_PASSWORD: ${{ secrets.AZURE_PG_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: |
          echo "Starting ENTSOE ETL..."
          python entsoe_etl.py || echo "ETL failed, see log file"

      - name: Upload logs and historical marker
        if: always()   # Upload even if previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: etl-artifacts
          path: |
            entsoe_etl.log
            .last_historical_run
