name: ENTSOE ETL

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose ETL mode"
        required: true
        default: "daily"
        type: choice
        options:
          - daily
          - historical
  schedule:
    - cron: '0 2 * * *'   # Runs daily at 02:00 UTC

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas psycopg2-binary requests pytz

      - name: Run ETL
        env:
          ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
          AZURE_PG_HOST: ${{ secrets.AZURE_PG_HOST }}
          AZURE_PG_DB: ${{ secrets.AZURE_PG_DB }}
          AZURE_PG_USER: ${{ secrets.AZURE_PG_USER }}
          AZURE_PG_PASSWORD: ${{ secrets.AZURE_PG_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: |
          if [ "${{ github.event.inputs.mode }}" = "historical" ]; then
            echo "Running historical load..."
            python entsoe_etl.py --historical
          else
            echo "Running daily load..."
            python entsoe_etl.py
          fi

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-log
          path: entsoe_etl.log
