
name: ENTSOE Data Job

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 6 * * *"   # runs daily at 06:00 UTC

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests psycopg2-binary pandas

      - name: Run ENTSOE Job
        env:
          ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
          SUPABASE_CONN: ${{ secrets.SUPABASE_CONN }}
        run: |
          python entsoe_etl.py
