name: ENTSOE ETL

on:
  push:
    branches:
      - main
  schedule:
    # Runs daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:   # <-- Manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas psycopg2-binary pytz

    # 4. Set environment variables from GitHub Secrets
    - name: Set environment variables
      run: |
        echo "ENTSOE_TOKEN=${{ secrets.ENTSOE_TOKEN }}" >> $GITHUB_ENV
        echo "AZURE_PG_HOST=${{ secrets.AZURE_PG_HOST }}" >> $GITHUB_ENV
        echo "AZURE_PG_DB=${{ secrets.AZURE_PG_DB }}" >> $GITHUB_ENV
        echo "AZURE_PG_USER=${{ secrets.AZURE_PG_USER }}" >> $GITHUB_ENV
        echo "AZURE_PG_PASSWORD=${{ secrets.AZURE_PG_PASSWORD }}" >> $GITHUB_ENV

    # 5. Run the ETL script
    - name: Run ETL
      run: python entsoe_etl_azure.py
